http:
  services:
    auth-service:
      loadBalancer:
        servers:
          - url: "http://auth-service:8080"
        healthCheck:
          path: "/actuator/health"
          interval: "10s"
          timeout: "3s"

    networking-service:
      loadBalancer:
        servers:
          - url: "http://networking-service:8080"
        healthCheck:
          path: "/actuator/health"
          interval: "10s"
          timeout: "3s"

    messenger-service:
      loadBalancer:
        servers:
          - url: "http://messenger-service:8080"
        healthCheck:
          path: "/actuator/health"
          interval: "10s"
          timeout: "3s"


    kafka-ui:
      loadBalancer:
        servers:
          - url: "http://kafka-ui:8080"
        healthCheck:
          path: "/actuator/health"
          interval: "10s"
          timeout: "3s"
