services:
#  traefik:
#    image: traefik:v3.4
#    container_name: traefik
#    restart: unless-stopped
#    security_opt:
#      - no-new-privileges:true
#    networks:
#      # Connect to the 'traefik_proxy' overlay network for inter-container communication across nodes
#      - proxy
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - ./certs:/certs:ro
#      - ./dynamic:/dynamic:ro
#      - ./traefic.yml:/traefic.yml:ro

  auth-service:
    container_name: auth-service
    build:
      context: ./component/AuthMicro
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
      - "9091:9091"
    env_file:
      - ./.env
    environment:
      POSTGRES_DB_HOST: ${AUTH_POSTGRES_DB_HOST}
      POSTGRES_DB: ${AUTH_POSTGRES_DB_NAME}
      POSTGRES_USER: ${AUTH_POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_DB_PASSWORD}
      POSTGRES_DB_INTERNAL_PORT: ${AUTH_POSTGRES_DB_INTERNAL_PORT}
      PGSSLMODE_STATUS: ${AUTH_PGSSLMODE_STATUS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      LOG_LEVEL: debug
    depends_on:
      auth-db-postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - auth-network
      - shared-network

  auth-db-postgres:
    container_name: auth-db-postgres
    image: postgres:16-alpine
    ports:
      - "${AUTH_POSTGRES_DB_EXTERNAL_PORT}:${AUTH_POSTGRES_DB_INTERNAL_PORT}"
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${AUTH_POSTGRES_DB_NAME}
      POSTGRES_USER: ${AUTH_POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U $AUTH_POSTGRES_DB_USER -d $AUTH_POSTGRES_DB_NAME'" ]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
    volumes:
      - auth-db-postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - auth-network


  networking-service:
    container_name: networking-service
    build:
      context: ./component/NetworkingMicro
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
      - "9092:9092"
    env_file:
      - ./.env
    environment:
      POSTGRES_DB_HOST: ${NETWORKING_POSTGRES_DB_HOST}
      POSTGRES_DB: ${NETWORKING_POSTGRES_DB_NAME}
      POSTGRES_DB_INTERNAL_PORT: ${NETWORKING_POSTGRES_DB_INTERNAL_PORT}
      POSTGRES_USER: ${NETWORKING_POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${NETWORKING_POSTGRES_DB_PASSWORD}
      PGSSLMODE_STATUS: ${NETWORKING_PGSSLMODE_STATUS}
      DB_AUTO_MIGRATE: true
      LOG_OUTPUT: file
      LOG_DIR: logs
    depends_on:
      networking-db-postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - networking-network
      - shared-network


  networking-db-postgres:
    container_name: networking-db-postgres
    image: postgres:16-alpine
    ports:
      - "${NETWORKING_POSTGRES_DB_EXTERNAL_PORT}:${NETWORKING_POSTGRES_DB_INTERNAL_PORT}"
    environment:
      PGPORT: ${NETWORKING_POSTGRES_DB_INTERNAL_PORT}
      POSTGRES_DB: ${NETWORKING_POSTGRES_DB_NAME}
      POSTGRES_USER: ${NETWORKING_POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${NETWORKING_POSTGRES_DB_PASSWORD}
    volumes:
      - networking-db-postgres:/var/lib/postgresql/data
      - ./component/NetworkingMicro/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U $NETWORKING_POSTGRES_DB_USER -d $NETWORKING_POSTGRES_DB_NAME'" ]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
    networks:
      - networking-network


volumes:
  auth-db-postgres:
  networking-db-postgres:


networks:
  shared-network:
    driver: bridge

  auth-network:
    driver: bridge
  networking-network:
    driver: bridge
