services:
  auth-service:
    container_name: auth-service
    build:
      context: ./component/AuthMicro
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${GRPC_PORT}:${GRPC_PORT}"
    env_file:
      - ./.env
    environment:
      PGHOST: ${AUTH_POSTGRES_DB_HOST}
      PGUSER: ${AUTH_POSTGRES_DB_USER}
      PGPASSWORD: ${AUTH_POSTGRES_DB_PASSWORD}
      PGDATABASE: ${AUTH_POSTGRES_DB_NAME}
      PGPORT: ${AUTH_POSTGRES_DB_INTERNAL_PORT}
      PGSSLMODE: ${AUTH_PGSSLMODE_STATUS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}  # minutes
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}  # 7 days in minutes
      HTTP_SERVER_ADDRESS: 0.0.0.0:${HTTP_PORT}
      GRPC_SERVER_ADDRESS: 0.0.0.0:${GRPC_PORT}
      LOG_LEVEL: debug
    depends_on:
      auth-db-postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - auth-network
      - shared-network

  auth-db-postgres:
    container_name: auth-db-postgres
    image: postgres:16-alpine
    ports:
      - "${AUTH_POSTGRES_DB_EXTERNAL_PORT}:${AUTH_POSTGRES_DB_INTERNAL_PORT}"
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${AUTH_POSTGRES_DB_NAME}
      POSTGRES_USER: ${AUTH_POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U $AUTH_POSTGRES_DB_USER -d $AUTH_POSTGRES_DB_NAME'" ]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
    volumes:
      - auth-db-postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - auth-network


  networking-service:
    container_name: networking-service
    build:
      context: ./component/NetworkingMicro
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - ./.env
    environment:
      DB_HOST: networking-db-postgres
      DB_NAME: ${NETWORKING_POSTGRES_DB_NAME}
      DB_PORT: ${NETWORKING_POSTGRES_DB_INTERNAL_PORT}
      DB_USER: ${NETWORKING_POSTGRES_DB_USER}
      DB_PASS: ${NETWORKING_POSTGRES_DB_PASSWORD}
      DB_SSLMODE: ${NETWORKING_PGSSLMODE_STATUS}
      DB_AUTO_MIGRATE: true
      LOG_OUTPUT: file
      LOG_DIR: logs
    depends_on:
      networking-db-postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - networking-network
      - shared-network
  
  networking-db-postgres:
    container_name: networking-db-postgres
    image: postgres:16-alpine
    ports:
      - "${NETWORKING_POSTGRES_DB_EXTERNAL_PORT}:${NETWORKING_POSTGRES_DB_INTERNAL_PORT}"
    environment:
      PGPORT: ${NETWORKING_POSTGRES_DB_INTERNAL_PORT}
      POSTGRES_DB: ${NETWORKING_POSTGRES_DB_NAME}
      POSTGRES_USER: ${NETWORKING_POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${NETWORKING_POSTGRES_DB_PASSWORD}
    volumes:
      - networking-db-postgres:/var/lib/postgresql/data
      - ./component/NetworkingMicro/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U $NETWORKING_POSTGRES_DB_USER -d $NETWORKING_POSTGRES_DB_NAME'" ]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
    networks:
      - networking-network


volumes:
  auth-db-postgres:
  networking-db-postgres:


networks:
  shared-network:
    driver: bridge

  auth-network:
    driver: bridge
  networking-network:
    driver: bridge
